import streamlit as st
import pandas as pd
import plotly.express as px


st.header("Waste emission by category")


df_list = ["MUNICIPAL",
        "HOUSEHOLD",
        "RECYCLING",
        "LANDFILL",
        "COMPOST",
        "INCINERATION",
        "INCINERATION_WITH",
        "INCINERATION_WITHOUT",
        "BULKY",
        "MW_CAP",
        "WEEE",
        "RECYCLING_SHARE",
        "LANDF_SHARE",
        "COMPST_SHARE",
        "INC_SHARE",
        "INC_WITH_SHARE",
        "INC_WITHOUT_SHARE",
        ]

# Same but with string and only first letter capitalized
df_list_str = ["Municipal",
            "Household",
            "Recycling",
            "Landfill",
            "Compost",
            "Incineration",
            "Incineration with energy recovery",
            "Incineration without energy recovery",
            "Bulky",
            "Municipal waste per capita",
            "WEEE",
            "Recycling share (%)",
            "Landfill share (%)",
            "Compost share (%)",
            "Incineration share (%)",
            "Incineration with energy recovery share (%)",
            "Incineration without energy recovery share (%)"
            ]
df_definitions= {"Municipal": "Municipal waste is defined as waste collected and treated by or for municipalities. It covers waste from households, including bulky waste, similar waste from commerce and trade, office buildings, institutions and small businesses, as well as yard and garden waste, street sweepings, the contents of litter containers, and market cleansing waste if managed as household waste. The definition excludes waste from municipal sewage networks and treatment, as well as waste from construction and demolition activities.",
                "Household": "Household waste refers to waste material usually generated in the residential environment. Waste with similar characteristics may be generated in other economic activities and can thus be treated and disposed of together with household waste.",
                "Recycling": "Recycling waste is waste that has been collected, processed, and reused. It can include materials like paper, metal, and plastic that have been recovered from the waste stream and used to make new products.",
                "Landfill": "Landfill waste is waste that is deposited in a landfill, which is a site where waste is placed and then covered with soil. Landfills are used to dispose of solid waste, including household trash, construction and demolition debris, and industrial waste.",
                "Compost": "Compost waste is organic waste that has been decomposed and recycled as a fertilizer and soil conditioner. Compost is made by breaking down organic waste, such as food scraps and yard waste, through the process of decomposition.",
                "Incineration": "Incineration waste is waste that has been burned in order to reduce its volume and reduce the risk of disease. Incineration can be used to dispose of solid, liquid, or gaseous waste.",
                "Incineration with energy recovery": "Incineration with energy recovery waste is waste that has been burned in order to generate electricity or steam. The heat generated during the burning process is used to power a generator or produce steam, which can be used to heat buildings or power industrial processes.",
                "Incineration without energy recovery": "Incineration without energy recovery is waste that has been burned in order to reduce its volume and reduce the risk of disease. Incineration can be used to dispose of solid, liquid, or gaseous waste.",
                "Bulky": "Bulky waste is waste that is too large or heavy to be easily handled or transported. It can include items like furniture, appliances, and construction debris.",
                "Municipal waste per capita": "Municipal waste per capita is a measure of the amount of municipal waste generated per person in a community. It is used as a way to compare the waste generation of different communities and to track trends over time.",
                "WEEE": "WEEE (Waste Electrical and Electronic Equipment) is waste generated by electronic devices, such as computers, cellphones, and TVs. It can contain hazardous materials and is often difficult to recycle.",
                "Recycling share (%)": "Recycling share is the percentage of waste that has been collected, processed, and reused. It can include materials like paper, metal, and plastic that have been recovered from the waste stream and used to make new products.",
                "Incineration with energy recovery share (%)": "Incineration with energy recovery share is the percentage of waste that has been burned in order to generate electricity or steam. The heat generated during the burning process is used to power a generator or produce steam, which can be used to heat buildings or power industrial processes.",
                "Landfill share (%)": "Landfill share is the percentage of waste that is deposited in a landfill, which is a site where waste is placed and then covered with soil. Landfills are used to dispose of solid waste, including household trash, construction and demolition debris, and industrial waste.",
                "Compost share (%)": "Compost share is the percentage of organic waste that has been decomposed and recycled as a fertilizer and soil conditioner. Compost is made by breaking down organic waste, such as food scraps and yard waste, through the process of decomposition.",
                "Incineration without energy recovery share (%)": "Incineration without energy recovery share is the percentage of waste that has been burned in order to reduce its volume and reduce the risk of disease. Incineration can be used to dispose of solid, liquid, or gaseous waste.",
                "Incineration share (%)": "Incineration share is the percentage of waste that has been burned in order to reduce its volume and reduce the risk of disease. Incineration can be used to dispose of solid, liquid, or gaseous waste.",
                }

# dropdown for the dataframe to display
category = st.selectbox("Category", df_list_str)
# write the appropriate definition

st.info("%s" % df_definitions[category])

# load the appropriate dataframe
data = pd.read_csv(".\dataframes\%s.csv" % df_list[df_list_str.index(category)])
# slider for the year
year = st.slider("Year", 1990, 2020, 2020)
# bar plot for the selected year
data = data[data["Year"] == year]
# remove countries starting with "OECD"
data = data[~data["Country"].str.startswith("OECD")]

data = data[data["Year"] == year].groupby("Country")[
    "Value"].mean()
    
fig = px.bar(data, orientation="h", text_auto=True)
# sort the values in descending order
fig.update_layout(yaxis_categoryorder="total ascending")
fig.update_xaxes(tickformat=".0f")
# bigger plot size
fig.update_layout(height=1000)
# add values on top of the bars
fig.update_traces(textposition='outside')



# no legend
fig.update_layout(showlegend=False)
# restrict max length of bar to not overlap with the text
fig.update_layout(uniformtext_minsize=8, uniformtext_mode='hide')
# match color of the streamlit slider for the bars

# fit the plot to the screen
st.plotly_chart(fig)


# subtitle for the line plot
st.subheader("Waste emission evolution")

# dropdown for the country
data = pd.read_csv(".\dataframes\%s.csv" % df_list[df_list_str.index(category)])
data = data[~data["Country"].str.startswith("OECD")]
country = st.selectbox("Country", data["Country"].unique())
# line plot of the evolution of the municipal waste emission for the selected country

data = data[data["Country"] == country]
fig = px.line(data, x="Year", y="Value", labels={
                "value": "Municipal waste emission/Year (Thousands of tonnes)"})
fig.update_layout(height=500)

st.plotly_chart(fig)